main: split_time.c closest_flight.c
	gcc -std=c99 -Wall split_time.c -o split_time
	gcc -std=c99 -Wall closest_flight.c -o closest_flight
	gcc -std=c99 -Wall sort_words.c -o sort_words
clean:
	rm -f split_time closest_flight sort_word
